#!/bin/bash

# GitHub Secrets Setup Guide
# This script provides instructions for setting up GitHub secrets

echo "🔐 GitHub Secrets Setup Instructions"
echo "===================================="
echo ""
echo "You need to add the following secrets to your GitHub repository:"
echo ""
echo "1. Go to: https://github.com/mishraabhi1987/react-learning/settings/secrets/actions"
echo ""
echo "2. Click 'New repository secret' and add:"
echo ""
echo "   Secret Name: REACT_APP_GEMINI_API_KEY"
echo "   Secret Value: AIzaSyAZdyN4mpuk0fe67pt4pVgs2HX0Z-iQjds"
echo ""
echo "3. Click 'Add secret'"
echo ""
echo "4. Click 'New repository secret' again and add:"
echo ""
echo "   Secret Name: REACT_APP_ACCESS_KEY"
echo "   Secret Value: mishragemini087"
echo ""
echo "5. Click 'Add secret'"
echo ""
echo "✅ After adding these secrets, GitHub Actions will automatically:"
echo "   - Build your React app with the environment variables"
echo "   - Deploy it to GitHub Pages"
echo "   - Your app will work perfectly with the API keys!"
echo ""
echo "🌐 Your live site will be available at:"
echo "   https://mishraabhi1987.github.io/react-learning"
echo ""
echo "💡 Tip: You can check the deployment status in the 'Actions' tab of your repository"
